### ISSUE TITLE
run  docsite start occurs error

### ISSUE THREAD

**Issue by lovepoem** [apache/incubator-dubbo-website#177]
run  `docsite start` occurs error

```javascript
192:dubbo-website wx$ docsite start
/usr/local/lib/node_modules/docsite/lib/generateHTMLFile.js:29
        defaultLanguage: siteConfig.defaultLanguage,
                                    ^

TypeError: Cannot read property 'defaultLanguage' of undefined
    at generateHTMLFile (/usr/local/lib/node_modules/docsite/lib/generateHTMLFile.js:29:37)
    at start (/usr/local/lib/node_modules/docsite/lib/start.js:65:3)
    at Object.<anonymous> (/usr/local/lib/node_modules/docsite/bin/docsite.js:25:5)
    at Module._compile (internal/modules/cjs/loader.js:722:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:733:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:775:12)
    at startup (internal/bootstrap/node.js:300:19)

```

**Comment by lovepoem** [comment]
https://github.com/txd-team/docsite/issues/17

**Comment by purple-force** [comment]
what are the versions of docsite and nodejs?

**Comment by lovepoem** [comment]
```
node -v
v11.2.0

docsite -V
1.3.2
```

**Comment by purple-force** [comment]
plz downgrade node to 10.x.x and try again.

**Comment by lovepoem** [comment]
I use  `npm restart docsite`

I seems ok now  , the site now startup
