### ISSUE TITLE
The user doc about sticky connection is wrong.

### ISSUE THREAD

**Issue by code4wt** [apache/incubator-dubbo-website#186]
The doc url: [http://dubbo.apache.org/zh-cn/docs/user/demos/stickiness.html](http://dubbo.apache.org/zh-cn/docs/user/demos/stickiness.html)

![image](https://user-images.githubusercontent.com/25877772/48883002-8a529200-ee58-11e8-969e-9cd74192bd4b.png)

I do like this, but got an error. As below:

```java
Caused by: org.xml.sax.SAXParseException; lineNumber: 28; columnNumber: 49; cvc-complex-type.3.2.2: 元素 'dubbo:protocol' 中不允许出现属性 'sticky'。
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.error(ErrorHandlerWrapper.java:134)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:396)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:284)
        ........
```

The sticky property cannot be configured in \<dubbo:protocol\>, please see another issue [incubator-dubbo #1538](https://github.com/apache/incubator-dubbo/issues/1538). Please update sticky doc to avoid confusing developers, thx.

**Comment by ralf0131** [comment]
Hi, would you please send a pull request?

**Comment by code4wt** [comment]
OK, I will send a PR to update it.

**Comment by lovepoem** [comment]
Fixed via https://github.com/apache/incubator-dubbo-website/pull/189
