### ISSUE TITLE
docsite build failed

### ISSUE THREAD

**Issue by ralf0131** [apache/incubator-dubbo-website#220]
Docsite version

```
➜  incubator-dubbo-website git:(asf-site) ✗ docsite -V
1.3.8
```
Error message when running docsite start:

```
➜  incubator-dubbo-website git:(asf-site) docsite start
fs.js:25
'use strict';
^

ReferenceError: internalBinding is not defined
    at fs.js:25:1
    at req_ (/Users/wangtao/work/apache-dubbo/incubator-dubbo-website/node_modules/natives/index.js:137:5)
    at Object.req [as require] (/Users/wangtao/work/apache-dubbo/incubator-dubbo-website/node_modules/natives/index.js:54:10)
    at Object.<anonymous> (/Users/wangtao/work/apache-dubbo/incubator-dubbo-website/node_modules/vinyl-fs/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/wangtao/work/apache-dubbo/incubator-dubbo-website/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
```

**Comment by ralf0131** [comment]
When running `rm -rf node_modules && npm install`, I got following error:


```
AttributeError: 'NoneType' object has no attribute 'groups'
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/wangtao/work/apache-dubbo/incubator-dubbo-website/node_modules/node-gyp/lib/configure.js:336:16)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
gyp ERR! System Darwin 18.2.0
gyp ERR! command "/usr/local/Cellar/node/11.5.0/bin/node" "/Users/wangtao/work/apache-dubbo/incubator-dubbo-website/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /Users/wangtao/work/apache-dubbo/incubator-dubbo-website/node_modules/node-sass
gyp ERR! node -v v11.5.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
Build failed with error code: 1
npm WARN The package react is included as both a dev and production dependency.
npm WARN The package react-dom is included as both a dev and production dependency.
```

**Comment by purple-force** [comment]
There are some problems for node-sass using node 11, plz use node 8.x and run `rm -rf node_modules && npm install` and try again

**Comment by ralf0131** [comment]
Thanks for the info. I have installed Node 8.x and it works. I am closing this issue for now.
