### ISSUE TITLE
Could not run docsite start

### ISSUE THREAD

**Issue by ralf0131** [apache/incubator-dubbo-website#354]
When I am running `docsite start` and `docsite build`, I got the following error:

```
module.js:550
    throw err;
    ^

Error: Cannot find module 'optimize-css-assets-webpack-plugin'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (~/work/apache-dubbo/incubator-dubbo-website/gulpfile.js:7:33)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
^C
```

**Comment by kezhenxu94** [comment]
> When I am running `docsite start` and `docsite build`, I got the following error:
> 
> ```
> module.js:550
>     throw err;
>     ^
> 
> Error: Cannot find module 'optimize-css-assets-webpack-plugin'
>     at Function.Module._resolveFilename (module.js:548:15)
>     at Function.Module._load (module.js:475:25)
>     at Module.require (module.js:597:17)
>     at require (internal/module.js:11:18)
>     at Object.<anonymous> (~/work/apache-dubbo/incubator-dubbo-website/gulpfile.js:7:33)
>     at Module._compile (module.js:653:30)
>     at Object.Module._extensions..js (module.js:664:10)
>     at Module.load (module.js:566:32)
>     at tryModuleLoad (module.js:506:12)
>     at Function.Module._load (module.js:498:3)
> ^C
> ```

maybe new dependencies are added after your last build, did you run `npm install` again?

**Comment by purple-force** [comment]
run `rm -rf node_modules && npm i` in the root and try again

**Comment by ralf0131** [comment]
Thanks @kezhenxu94 @purple-force That works for me!
