### ISSUE TITLE
docsite build failed both on Windows&MacOS.

### ISSUE THREAD

**Issue by kimmking** [apache/incubator-dubbo-website#55]
D:\git\alibaba\incubator-dubbo-website>docsite build
C:\Users\kk\AppData\Roaming\npm\node_modules\docsite\lib\generateJSONFile.js:23
            ...result.meta,
            ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\kk\AppData\Roaming\npm\node_modules\docsite\lib\start.js:5

D:\git\alibaba\incubator-dubbo-website>npm run build

> dubbo-site@0.0.1 build D:\git\alibaba\incubator-dubbo-website
> rm -rf build && gulp build

[23:31:33] Using gulpfile D:\git\alibaba\incubator-dubbo-website\gulpfile.js
[23:31:33] Starting 'webpack:build'...
[BABEL] Note: The code generator has deoptimised the styling of "D:/git/alibaba/incubator-dubb
n" as it exceeds the max of "500KB".
[23:31:43] [webpack:build] Hash: 593f6334db0e3d48cde4
Version: webpack 2.7.0
Time: 9286ms
                  Asset     Size  Chunks                    Chunk Names
3769542dc85a905d2f4a.js  1.43 MB       0  [emitted]  [big]
1ecbed914a98e77c9bc7.js   250 kB       1  [emitted]  [big]
acbc28a1725c85d6763d.js  78.4 kB       2  [emitted]

**Comment by ralf0131** [comment]
@purple-force Could you please take a look at this issue?

**Comment by purple-force** [comment]
the version of node should >= 8.6.0

**Comment by kimmking** [comment]
升级到10.x也不行，用的n stable

**Comment by diecui1202** [comment]
Any further ?

**Comment by purple-force** [comment]
the version of docsite that the site used has upgrade to 1.x,plz upgrade it

**Comment by purple-force** [comment]
see https://txd-team.github.io/docsite-doc-v1/

**Comment by ralf0131** [comment]
@kimmking Is your problem solved?
